use crate::ir::{Guard, ShellConfig};
use crate::ports::ShellEmitter;

pub struct FishEmitter;

fn guard_check(guard: &Guard) -> String {
    match guard {
        Guard::CommandExists(cmd) => format!("command -q {cmd}"),
        Guard::PathExists(path) => format!("test -e \"{path}\""),
    }
}

impl ShellEmitter for FishEmitter {
    fn id(&self) -> &'static str {
        "fish"
    }

    fn ext(&self) -> &'static str {
        "fish"
    }

    fn emit(&self, config: &ShellConfig) -> String {
        let mut out = String::from("# generated by notshell — do not edit by hand\n\n");

        for var in &config.env {
            let line = format!("set -gx {} \"{}\"\n", var.name, var.value);
            match &var.guard {
                Some(g) => out.push_str(&format!("if {}\n    {}end\n", guard_check(g), line)),
                None => out.push_str(&line),
            }
        }

        if !config.env.is_empty() {
            out.push('\n');
        }

        for entry in &config.path {
            let flags = if entry.prepend { " --prepend" } else { "" };
            let line = format!("fish_add_path{flags} \"{}\"\n", entry.dir);
            match &entry.guard {
                Some(g) => out.push_str(&format!("if {}\n    {}end\n", guard_check(g), line)),
                None => out.push_str(&line),
            }
        }

        if !config.path.is_empty() {
            out.push('\n');
        }

        for alias in &config.aliases {
            match (&alias.guard, &alias.else_command) {
                (Some(g), Some(else_cmd)) => out.push_str(&format!(
                    "if {check}\n    alias {name} \"{cmd}\"\nelse\n    alias {name} \"{else_cmd}\"\nend\n",
                    check = guard_check(g),
                    name = alias.name,
                    cmd = alias.command,
                )),
                (Some(g), None) => out.push_str(&format!(
                    "if {check}\n    alias {name} \"{cmd}\"\nend\n",
                    check = guard_check(g),
                    name = alias.name,
                    cmd = alias.command,
                )),
                (None, _) => {
                    out.push_str(&format!("alias {} \"{}\"\n", alias.name, alias.command))
                }
            }
        }

        out
    }
}
