use crate::ir::{Guard, ShellConfig};
use crate::ports::ShellEmitter;

pub struct NuEmitter;

fn guard_check(guard: &Guard) -> String {
    match guard {
        Guard::CommandExists(cmd) => format!("(which {cmd} | is-not-empty)"),
        Guard::PathExists(path) => format!("(\"{path}\" | path expand | path exists)"),
    }
}

impl ShellEmitter for NuEmitter {
    fn id(&self) -> &'static str {
        "nu"
    }

    fn ext(&self) -> &'static str {
        "nu"
    }

    fn emit(&self, config: &ShellConfig) -> String {
        let mut out = String::from("# generated by notshell — do not edit by hand\n\n");

        for var in &config.env {
            let line = format!("$env.{} = \"{}\"\n", var.name, var.value);
            match &var.guard {
                Some(g) => out.push_str(&format!(
                    "if {} {{\n  {}}}\n",
                    guard_check(g),
                    line.replace('\n', "\n  ").trim_end().to_string() + "\n"
                )),
                None => out.push_str(&line),
            }
        }

        if !config.env.is_empty() {
            out.push('\n');
        }

        for entry in &config.path {
            let expr = if entry.prepend {
                format!("$env.PATH = ($env.PATH | prepend \"{}\")\n", entry.dir)
            } else {
                format!("$env.PATH = ($env.PATH | append \"{}\")\n", entry.dir)
            };
            match &entry.guard {
                Some(g) => out.push_str(&format!("if {} {{\n  {}}}\n", guard_check(g), expr)),
                None => out.push_str(&expr),
            }
        }

        if !config.path.is_empty() {
            out.push('\n');
        }

        for alias in &config.aliases {
            match (&alias.guard, &alias.else_command) {
                (Some(g), Some(else_cmd)) => out.push_str(&format!(
                    "if {check} {{\n  alias {name} = {cmd}\n}} else {{\n  alias {name} = {else_cmd}\n}}\n",
                    check = guard_check(g),
                    name = alias.name,
                    cmd = alias.command,
                )),
                (Some(g), None) => out.push_str(&format!(
                    "if {check} {{\n  alias {name} = {cmd}\n}}\n",
                    check = guard_check(g),
                    name = alias.name,
                    cmd = alias.command,
                )),
                (None, _) => {
                    out.push_str(&format!("alias {} = {}\n", alias.name, alias.command))
                }
            }
        }

        out
    }
}
