[package]
name = "integration"
version = "0.1.0"
edition = "2024"
license.workspace = true
publish = true

[[test]]
name = "bootstrap"
path = "tests/bootstrap.rs"

[[test]]
name = "cross_crate"
path = "tests/cross_crate.rs"

[[test]]
name = "doctor"
path = "tests/doctor.rs"

[dev-dependencies]
anyhow    = { workspace = true }
assert_fs = { workspace = true }
notcore = { workspace = true } #unified
notfiles = { workspace = true } #unified
nothooks = { workspace = true } #unified
notsecrets = { workspace = true } #unified
notstrap = { workspace = true } #unified
tempfile  = { workspace = true }
